### ISSUE TITLE
Wrong test class name is generated when using scaffolding

### ISSUE THREAD

**Issue by phortx** [bullet-train-co/bullet_train#572] opened 2022-12-27 15:20 UTC
`posts_controller_test.rb` contains:

```
module Api
  module V1
    module Scaffolding
      module CompletelyConcrete
        class TangibleThingsControllerTest < Api::Test
```

Instead of `PostsControllerTest`

**Comment by gazayas** [comment] 2022-12-28 09:57
@phortx Would you mind posting the steps you took to scaffold `Posts`? For example, I entered these commands:
```
> rails g model Post team:references title:string
> bin/super-scaffold crud Post Team title:text_field
```

This scaffolds the following in `test/controllers/api/v1/posts_controller_test.rb`:
```ruby
require "controllers/api/v1/test"

class Api::V1::PostsControllerTest < Api::Test
  ...
end
```

**Comment by jagthedrummer** [comment] 2023-08-28 20:01
@phortx, any chance you could help us out with some reproduction steps?

**Comment by jagthedrummer** [comment] 2023-10-03 18:10
I'm going to close this since we haven't been able to reproduce it. @phortx, feel free to reopen this and include some reproduction steps if it's still giving you problems.

**Closed by jagthedrummer** 2023-10-03 18:10 UTC
