### ISSUE TITLE
undefined method `user' for nil:NilClass in membership_profile_photo_url

### ISSUE THREAD

**Issue by jlneto** [bullet-train-co/bullet_train#448] opened 2022-09-27 16:20 UTC
Very frequently I have a problem when membership is null for the current user and I get the following error:

```
NoMethodError: undefined method `user' for nil:NilClass
    if membership.user
                 ^^^^^
GEM_ROOT]/gems/bullet_train-1.1.7/app/helpers/account/users_helper.rb:28:in `membership_profile_photo_url'
26	
27	  def membership_profile_photo_url(membership)
28	    if membership.user
29	      user_profile_photo_url(membership.user)
30	    else
```

Somehow, current_team became incompatible with current_user, and membership became nil. 

To hard_fix that I changed current_team to fix it when it happens like this:

```
def current_team
  # TODO We do not want this to be based on the `current_team_id`.
  # TODO We want this to be based on the current resource being loaded.
  membership = current_user.memberships.find_by(team_id: current_user.current_team_id)
  team = membership.team if membership
  unless team
    membership = current_user.memberships.first
    team = membership.team if membership
    if team
      current_user.current_team_id = team.id
      current_user.save!
    end
  end
  team
end
```

I am not fixing the root cause but allowing the user to use the app.
bullet_train (1.1.7)
bullet_train-themes (1.0.23)
bullet_train-themes-tailwind_css (1.0.16)

**Comment by gazayas** [comment] 2022-09-30 00:44
Hello @jlneto, I'm trying to duplicate it here locally but haven't gotten the error yet. Would you mind providing the view it's happening on along with the full error logs?

Just to make sure, the `current_team` method you edited is [here](https://github.com/bullet-train-co/bullet_train-base/blob/7c3abb00be74322677f24deb10670c0f76d863da/app/helpers/account/teams_helper.rb#L2), correct?

I saw there's a TODO there so I'll look into that in the meantime.

**Comment by jagthedrummer** [comment] 2023-08-25 18:49
@jlneto, any chance you could help us understand the reproduction steps needed to make this problem happen?

**Comment by jagthedrummer** [comment] 2023-09-19 16:13
I'm going to close this for now since we don't have more details. We should definitely reopen it if we can get some reproduction steps.

**Closed by jagthedrummer** 2023-09-19 16:13 UTC
