### ISSUE TITLE
Double scrolling issue on iOS.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#381] opened 2022-08-24 14:19 UTC
![2C42AFCF-1D36-44C9-9D08-C423A6925171](https://user-images.githubusercontent.com/217218/186442179-c8b5a881-6255-47d7-aab7-206c9967a9c7.jpeg)

**Comment by andrewculver** [comment] 2022-08-24 14:20
@gazayas Do you have an iOS device to try and reproduce this? No problem if not, just wanted to check before I assign it.

**Comment by vsnguyen** [comment] 2022-08-25 03:26
I'm about 80% certain that it has something to do with the `overflow-hidden` used in `account/shared/box`.

**Comment by gazayas** [comment] 2022-08-25 04:31
@andrewculver I have XCode on my mac and an iPhone as well, so I'll try to reproduce the issue.

**Comment by gazayas** [comment] 2022-09-14 03:51
@vsnguyen Swinging back to this one now, I just want to make sure I understand the issue.

By double scrolling do you mean that if you scroll all the way to the top or bottom, you have to scroll one more time to reveal all the content? Video example here:
https://user-images.githubusercontent.com/10546292/190055374-3b5a4936-3bca-41c7-a780-2a88a2ef3a13.MOV

And yes, this doesn't happen for me on Chrome with the browser tools:
https://user-images.githubusercontent.com/10546292/190055448-3ceeccc6-cb10-4c4e-9655-0d39e9d4c6f6.MOV

**Comment by gazayas** [comment] 2022-09-14 03:52
The videos might not work, give me a minute and I'll try to re-upload

**Comment by vsnguyen** [comment] 2022-09-14 08:01
@gazayas yup!

**Comment by jagthedrummer** [comment] 2023-08-25 18:41
@gazayas, is there still something to be done here after the merge of https://github.com/bullet-train-co/bullet_train/pull/423?

**Comment by gazayas** [comment] 2023-08-28 11:39
@jagthedrummer I don't believe so, I think the issue is more of an iOS one than a Bullet Train one. I think we can close the issue.

**Closed** 2023-08-28 15:40 UTC
